BEGIN;

CREATE TABLE IF NOT EXISTS mlb_player_game_stats (
    sport_key TEXT NOT NULL,
    season INT NOT NULL,
    game_id INT NOT NULL,
    player_id INT NOT NULL,
    team_name TEXT,
    at_bats INT,
    runs INT,
    hits INT,
    rbi INT,
    hr INT,
    bb INT,
    k INT,
    avg NUMERIC,
    obp NUMERIC,
    slg NUMERIC,
    doubles INT,
    triples INT,
    intentional_walks INT,
    hit_by_pitch INT,
    stolen_bases INT,
    caught_stealing INT,
    plate_appearances INT,
    total_bases INT,
    left_on_base INT,
    fly_outs INT,
    ground_outs INT,
    line_outs INT,
    pop_outs INT,
    air_outs INT,
    gidp INT,
    sac_bunts INT,
    sac_flies INT,
    ip NUMERIC,
    p_hits INT,
    p_runs INT,
    er INT,
    p_bb INT,
    p_k INT,
    p_hr INT,
    pitch_count INT,
    strikes INT,
    era NUMERIC,
    batters_faced INT,
    pitching_outs INT,
    wins INT,
    losses INT,
    saves INT,
    holds INT,
    blown_saves INT,
    games_started INT,
    wild_pitches INT,
    balks INT,
    pitching_hbp INT,
    inherited_runners INT,
    inherited_runners_scored INT,
    putouts INT,
    assists INT,
    errors INT,
    fielding_chances INT,
    fielding_pct NUMERIC,
    provider TEXT NOT NULL,
    PRIMARY KEY (sport_key, season, game_id, player_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_mlb_player_stats_by_player
    ON mlb_player_game_stats (sport_key, player_id, season, game_id);

CREATE INDEX IF NOT EXISTS idx_mlb_player_stats_by_game
    ON mlb_player_game_stats (sport_key, season, game_id);

COMMIT;